//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Colisao.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_COLISAO_H)
#define _COLISAO_H


class Colisao {
public:
	bool colidir(int Ax, int Ay, int Bx, int By, int Aw, int Ah, int Bw, int Bh, int nt);
private:
	bool colidiu;
};

#endif  //_COLISAO_H
