//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : exportar.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_EXPORTAR_H)
#define _EXPORTAR_H


class exportar {
};

#endif  //_EXPORTAR_H
