//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : heroi.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_HEROI_H)
#define _HEROI_H

#include "Personagens.h"

class heroi : public Personagens {
public:
	heroi();
	~heroi();
};

#endif  //_HEROI_H
