//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Mapa.h
//  @ Date : 05/05/2018
//  @ Author :
//
//


#if !defined(_MAPA_H)
#define _MAPA_H


class Mapa {

private:
	int width;
	int height;
	int x;
	int y;
	int fase;
	int ntile;

public:
    Mapa();
	~Mapa();

	void iniciaAllegro();
	void criafase(int y1, int x1, int w1, int h1);
	virtual void setSpriteBloco();

};

#endif  //_MAPA_H
