//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstaculo.h
//  @ Date : 05/05/2018
//  @ Author :
//
//


#if !defined(_OBSTACULO_H)
#define _OBSTACULO_H

#include "Mapa.h"

class Obstaculo : public Mapa {
public:
	Obstaculo();
	~Obstaculo();
	void setSpriteBloco(int ntile);
	void criaObstaculo(int y1, int x1, int w1, int h1);
};

#endif  //_OBSTACULO_H
