//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sprites.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_SPRITES_H)
#define _SPRITES_H


class Sprites {
public:
	int x;
	int y;
	int w;
	int h;
};

#endif  //_SPRITES_H
