//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TXT.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_TXT_H)
#define _TXT_H


class TXT {
};

#endif  //_TXT_H
