//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : vilao.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_VILAO_H)
#define _VILAO_H

#include "Personagens.h"

class vilao : public Personagens {
public:
	vilao();
	~vilao();
};

#endif  //_VILAO_H
