//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : XLS.h
//  @ Date : 05/05/2018
//  @ Author : 
//
//


#if !defined(_XLS_H)
#define _XLS_H


class XLS {
};

#endif  //_XLS_H
