//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Colisao.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/Colisao.h"

bool Colisao::colidir(int Ax, int Ay, int Bx, int By, int Aw, int Ah, int Bw, int Bh, int nt) {

}

