//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : heroi.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/heroi.h"

heroi::heroi() {

}

heroi::~heroi() {

}

