//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Mapa.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/Mapa.h"

void Mapa::iniciaAllegro() {

}

void Mapa::criafase(int y1, int x1, int w1, int h1) {

}

void Mapa::setSpriteBloco() {

}

Mapa::Mapa() {

}

Mapa::~Mapa() {

}

