//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstaculo.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/Obstaculo.h"

Obstaculo::Obstaculo() {

}

Obstaculo::~Obstaculo() {

}

void Obstaculo::setSpriteBloco(int ntile) {

}

void Obstaculo::criaObstaculo(int y1, int x1, int w1, int h1) {

}

