//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Personagens.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/Personagens.h"

Personagens::Personagens() {

}

Personagens::~Personagens() {

}

void Personagens::setAtributos(int x, int y, int w, int h, int tx, int ty) {

}

int Personagens::getVida() {

}

int Personagens::getTamanhox() {

}

int Personagens::getTamanhoy() {

}

int Personagens::getWidth() {

}

int Personagens::getHeigth() {

}

