//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : vilao.cpp
//  @ Date : 05/05/2018
//  @ Author :
//
//


#include "../include/vilao.h"

vilao::vilao() {

}

vilao::~vilao() {

}

